### PR TITLE
Enables antigen usage

### PR DESCRIPTION
**Pull request by fuero**
Incorporates PR #38

### CODE REVIEW

**Comment by shimarulin** [comment]
Hi @fuero! To enable load this plugin with Zplugin too, I renamed `zsh-histdb.plugin.sh` to `zsh-histdb.plugin.zsh` in commit f075c5a1ad39fea9d212c63777c1276d2dfc21bb in my own fork https://github.com/shimarulin/zsh-histdb. This will work for the antigen as well (I'm not antigen user)?

**Comment by sumanthratna** [comment]
Hi @larkery! I'm not a fan of mentioning people who haven't yet commented on a PR/issue, but could you take a look at this? The only thing holding me back from using zsh-histdb is that there's no antibody compatibility yet. 

If you'd like for me test it out (I'm on macOS 10.15.5 Beta), I'd be happy to do so.

**Comment by larkery** [comment]
Hello

I don't mind being mentioned, but this project has a very low quality-of-service guarantee.

As far as I can see this change does three things:

1. Change the variable declaration for boring commands. I don't fully understand why this is necessary (i.e. why it doesn't break for some people), but it seems reasonable
2. Put in this mysterious plugin file which presumably has something to do with however antigen works - I don't use antigen or other configuration frameworks, so I have no idea whether it is correct. On the other hand it doesn't look dangerous, and it's no skin off my back to put it in there. If anyone else is reading this who knows and cares about antigen or its equivalents wants to review this I would be interested to hear opinions. I'm not going to learn antigen so I can do it myself.
3. Move the merge driver and modify the user's PATH to point at it. This I don't like, as I don't want to modify the user's PATH to contain the merge driver as it's not a command you'd be likely to use interactively, and this will break people's existing configurations which use the old location.

So, if you are OK to adjust 3. back how it was, I am OK to merge the other two changes.

Does anyone know why the `declare -ga` is required for some people but not for others? People in #38?

It'd be good to understand this.

**Comment by larkery** [comment]
I think I have accommodated these requirements on master.

**Comment by sumanthratna** [comment]
Just to confirm: I think this works with antibody (so this should also work with antigen). I'm not totally sure because of #80 but the ` histdb-top` top command works so I'm assuming the installation worked.

**Pull request closed without merging**
